package br.org.ccb.sgh.integrated.controller;

import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.Matchers.endsWith;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.util.Locale;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockitoAnnotations;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.context.junit.jupiter.web.SpringJUnitWebConfig;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.servlet.i18n.FixedLocaleResolver;

import com.fasterxml.jackson.databind.ObjectMapper;

import br.org.ccb.sgh.TestUtils;
import br.org.ccb.sgh.controller.ReservationController;
import br.org.ccb.sgh.controller.handler.ResourceExceptionHandler;
import br.org.ccb.sgh.http.dto.ReservationDto;
import br.org.ccb.sgh.http.dto.ReservationStatusDto;

@Sql(scripts = {"classpath:sql/drop.sql", "classpath:sql/create.sql", "classpath:sql/populate.sql"})
@SpringBootTest
@ExtendWith(SpringExtension.class)
@SpringJUnitWebConfig
public class ReservationControllerTest {

	private static final String URL = "/reservations";
	private static final String BY_ID = URL.concat("/1");
	private MockMvc mockMvc;
	private AutoCloseable closeable;

	@Autowired
	private ReservationController reservationController;
	
	@BeforeEach
	void setUp() {
		this.mockMvc = MockMvcBuilders.standaloneSetup(reservationController)
				.setControllerAdvice(new ResourceExceptionHandler()).setLocaleResolver(new FixedLocaleResolver(new Locale("pt", "BR"))).build();
		closeable = MockitoAnnotations.openMocks(this);
	}
	
	@AfterEach
	void releaseMocks() throws Exception {
		closeable.close();
	}
	
	@Test
	void saveSuccessTest() throws Exception {
		this.mockMvc
				.perform(post(URL).content(new ObjectMapper().writeValueAsString(TestUtils.createReservationDto()))
						.contentType(MediaType.APPLICATION_JSON))
				.andExpect(status().isCreated()).andExpect(header().exists("location"))
				.andExpect(header().string("location", endsWith(URL.concat("/2"))));
	}
	
	@Test
	void findByIdSuccessTest() throws Exception {
		this.mockMvc.perform(get(BY_ID).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
				.andExpect(jsonPath("id", is(1))).andExpect(jsonPath("initialDate[0]", is(2020)))
				.andExpect(jsonPath("initialDate[1]", is(11)))
				.andExpect(jsonPath("initialDate[2]", is(1)))
				.andExpect(jsonPath("finalDate[0]", is(2020)))
				.andExpect(jsonPath("finalDate[1]", is(11)))
				.andExpect(jsonPath("finalDate[2]", is(9)))
				.andExpect(jsonPath("checkinDate[0]", is(2020)))
				.andExpect(jsonPath("checkinDate[1]", is(11)))
				.andExpect(jsonPath("checkinDate[2]", is(9)))
				.andExpect(jsonPath("checkoutDate[0]", is(2020)))
				.andExpect(jsonPath("checkoutDate[1]", is(11)))
				.andExpect(jsonPath("checkoutDate[2]", is(12)))
				.andExpect(jsonPath("observation", is("none"))).andExpect(jsonPath("status", is("CONFIRMED")))
				.andExpect(jsonPath("guests[0].name", is("Guest 1")))
				.andExpect(jsonPath("guests[0].dateOfBirth[0]", is(2000)))
				.andExpect(jsonPath("guests[0].dateOfBirth[1]", is(12)))
				.andExpect(jsonPath("guests[0].dateOfBirth[2]", is(11)))
				.andExpect(jsonPath("guests[0].phoneNumber", is("1658741258")))
				.andExpect(jsonPath("guests[0].celNumber", is("18966547890")))
				.andExpect(jsonPath("guests[0].rg", is("126547854")))
				.andExpect(jsonPath("guests[0].cpf", is("19290228083")))
				.andExpect(jsonPath("guests[0].ministery", is(true)))
				.andExpect(jsonPath("guests[0].baptized", is(true)))
				.andExpect(jsonPath("guests[0].dateOfBaptism[0]", is(2019)))
				.andExpect(jsonPath("guests[0].dateOfBaptism[1]", is(1)))
				.andExpect(jsonPath("guests[0].dateOfBaptism[2]", is(1)))
				.andExpect(jsonPath("guests[0].prayingHouse", is("Central")))
				.andExpect(jsonPath("guests[0].observation", is("observation")))
				.andExpect(jsonPath("guests[0].address.id", is(1)))
				.andExpect(jsonPath("guests[0].address.street", is("Street")))
				.andExpect(jsonPath("guests[0].address.city", is("Test")))
				.andExpect(jsonPath("guests[0].address.district", is("District")))
				.andExpect(jsonPath("guests[0].address.number", is("1F")))
				.andExpect(jsonPath("guests[0].address.state", is("SP")))
				.andExpect(jsonPath("guests[0].address.zipCode", is("11111111")))
				.andExpect(jsonPath("guests[1].id", is(2))).andExpect(jsonPath("guests[1].name", is("Guest 2")))
				.andExpect(jsonPath("guests[1].dateOfBirth[0]", is(2001)))
				.andExpect(jsonPath("guests[1].dateOfBirth[1]", is(11)))
				.andExpect(jsonPath("guests[1].dateOfBirth[2]", is(10)))
				.andExpect(jsonPath("guests[1].phoneNumber", is("1166987451")))
				.andExpect(jsonPath("guests[1].celNumber", is("11988887746")))
				.andExpect(jsonPath("guests[1].rg", is("226547854")))
				.andExpect(jsonPath("guests[1].cpf", is("24953683013")))
				.andExpect(jsonPath("guests[1].ministery", is(false)))
				.andExpect(jsonPath("guests[1].baptized", is(false)))
				.andExpect(jsonPath("guests[1].dateOfBaptism[0]", is(2018)))
				.andExpect(jsonPath("guests[1].dateOfBaptism[1]", is(12)))
				.andExpect(jsonPath("guests[1].dateOfBaptism[2]", is(12)))
				.andExpect(jsonPath("guests[1].prayingHouse", is("Central")))
				.andExpect(jsonPath("guests[1].observation", is("observation")))
				.andExpect(jsonPath("guests[1].address.id", is(2)))
				.andExpect(jsonPath("guests[1].address.street", is("Street2")))
				.andExpect(jsonPath("guests[1].address.city", is("Test2")))
				.andExpect(jsonPath("guests[1].address.district", is("District2")))
				.andExpect(jsonPath("guests[1].address.number", is("1G")))
				.andExpect(jsonPath("guests[1].address.state", is("MG")))
				.andExpect(jsonPath("guests[1].address.zipCode", is("22222222")))
				.andExpect(jsonPath("contact.id", is(1))).andExpect(jsonPath("contact.name", is("Contact 1")))
				.andExpect(jsonPath("contact.phoneNumber", is("1666987450")))
				.andExpect(jsonPath("contact.celNumber", is("16988887745")))
				.andExpect(jsonPath("contact.ministery", is("Diácono")))
				.andExpect(jsonPath("contact.relationship", is("Irmão")))
				.andExpect(jsonPath("contact.observation", is("obs")))
				.andExpect(jsonPath("contact.address.id", is(1)))
				.andExpect(jsonPath("contact.address.street", is("Street")))
				.andExpect(jsonPath("contact.address.city", is("Test")))
				.andExpect(jsonPath("contact.address.district", is("District")))
				.andExpect(jsonPath("contact.address.number", is("1F")))
				.andExpect(jsonPath("contact.address.state", is("SP")))
				.andExpect(jsonPath("contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?limit=1")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByIDSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?id=1")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByInitialDateSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?initialDate=01/11/2020")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByFinalDateSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?finalDate=09/11/2020")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByCheckinDatedSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?checkinDate=09/11/2020")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByCheckoutDateSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?checkoutDate=12/11/2020")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByRoomIdSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?roomId=1")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByRoomNameSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?roomName=Room 1")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByGuestIdSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?guestId=2")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByGuestNameSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?guestName=Guest 2")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByContactIdSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?contactId=1")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByContactNameSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?contactName=Contact 1")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringBySupportHouseIdSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?supportHouseId=1")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void findAllFilteringByStatusSuccessTest() throws Exception {
		this.mockMvc.perform(get(URL.concat("?status=CONFIRMED")).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("$.content", hasSize(1))).andExpect(jsonPath("$.content.[0].id", is(1)))
		.andExpect(jsonPath("$.content.[0].initialDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].initialDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].initialDate[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].finalDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].finalDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].finalDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkinDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkinDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkinDate[2]", is(9)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[0]", is(2020)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].checkoutDate[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].observation", is("none")))
		.andExpect(jsonPath("$.content.[0].status", is("CONFIRMED")))
		.andExpect(jsonPath("$.content.[0].guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("$.content.[0].guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("$.content.[0].guests[0].rg", is("126547854")))
		.andExpect(jsonPath("$.content.[0].guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("$.content.[0].guests[0].ministery", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].baptized", is(true)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[0].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].guests[0].address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("$.content.[0].guests[1].id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("$.content.[0].guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("$.content.[0].guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("$.content.[0].guests[1].rg", is("226547854")))
		.andExpect(jsonPath("$.content.[0].guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("$.content.[0].guests[1].ministery", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].baptized", is(false)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("$.content.[0].guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("$.content.[0].guests[1].observation", is("observation")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.id", is(2)))
		.andExpect(jsonPath("$.content.[0].guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.district", is("District2")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.number", is("1G")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.state", is("MG")))
		.andExpect(jsonPath("$.content.[0].guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("$.content.[0].contact.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.name", is("Contact 1")))
		.andExpect(jsonPath("$.content.[0].contact.phoneNumber", is("1666987450")))
		.andExpect(jsonPath("$.content.[0].contact.celNumber", is("16988887745")))
		.andExpect(jsonPath("$.content.[0].contact.ministery", is("Diácono")))
		.andExpect(jsonPath("$.content.[0].contact.relationship", is("Irmão")))
		.andExpect(jsonPath("$.content.[0].contact.observation", is("obs")))
		.andExpect(jsonPath("$.content.[0].contact.address.id", is(1)))
		.andExpect(jsonPath("$.content.[0].contact.address.street", is("Street")))
		.andExpect(jsonPath("$.content.[0].contact.address.city", is("Test")))
		.andExpect(jsonPath("$.content.[0].contact.address.district", is("District")))
		.andExpect(jsonPath("$.content.[0].contact.address.number", is("1F")))
		.andExpect(jsonPath("$.content.[0].contact.address.state", is("SP")))
		.andExpect(jsonPath("$.content.[0].contact.address.zipCode", is("11111111")));
	}
	
	@Test
	void updateSuccessTest() throws Exception {
		ReservationDto reservationDto = TestUtils.createReservationDto();
		this.mockMvc
				.perform(put(BY_ID).content(new ObjectMapper().writeValueAsString(reservationDto))
						.contentType(MediaType.APPLICATION_JSON))
				.andExpect(status().isNoContent());
		this.mockMvc.perform(get(BY_ID).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("id", is(1))).andExpect(jsonPath("initialDate[0]", is(reservationDto.getInitialDate().getYear())))
		.andExpect(jsonPath("initialDate[1]", is(reservationDto.getInitialDate().getMonthValue())))
		.andExpect(jsonPath("initialDate[2]", is(reservationDto.getInitialDate().getDayOfMonth())))
		.andExpect(jsonPath("finalDate[0]", is(reservationDto.getFinalDate().getYear())))
		.andExpect(jsonPath("finalDate[1]", is(reservationDto.getFinalDate().getMonthValue())))
		.andExpect(jsonPath("finalDate[2]", is(reservationDto.getFinalDate().getDayOfMonth())))
		.andExpect(jsonPath("checkinDate[0]", is(reservationDto.getCheckinDate().getYear())))
		.andExpect(jsonPath("checkinDate[1]", is(reservationDto.getCheckinDate().getMonthValue())))
		.andExpect(jsonPath("checkinDate[2]", is(reservationDto.getCheckinDate().getDayOfMonth())))
		.andExpect(jsonPath("checkoutDate[0]", is(reservationDto.getCheckoutDate().getYear())))
		.andExpect(jsonPath("checkoutDate[1]", is(reservationDto.getCheckoutDate().getMonthValue())))
		.andExpect(jsonPath("checkoutDate[2]", is(reservationDto.getCheckoutDate().getDayOfMonth())))
		.andExpect(jsonPath("observation", is(reservationDto.getObservation()))).andExpect(jsonPath("status", is(reservationDto.getStatus())))
		.andExpect(jsonPath("guests[0].name", is("Guest 1")))
		.andExpect(jsonPath("guests[0].dateOfBirth[0]", is(2000)))
		.andExpect(jsonPath("guests[0].dateOfBirth[1]", is(12)))
		.andExpect(jsonPath("guests[0].dateOfBirth[2]", is(11)))
		.andExpect(jsonPath("guests[0].phoneNumber", is("1658741258")))
		.andExpect(jsonPath("guests[0].celNumber", is("18966547890")))
		.andExpect(jsonPath("guests[0].rg", is("126547854")))
		.andExpect(jsonPath("guests[0].cpf", is("19290228083")))
		.andExpect(jsonPath("guests[0].ministery", is(true)))
		.andExpect(jsonPath("guests[0].baptized", is(true)))
		.andExpect(jsonPath("guests[0].dateOfBaptism[0]", is(2019)))
		.andExpect(jsonPath("guests[0].dateOfBaptism[1]", is(1)))
		.andExpect(jsonPath("guests[0].dateOfBaptism[2]", is(1)))
		.andExpect(jsonPath("guests[0].prayingHouse", is("Central")))
		.andExpect(jsonPath("guests[0].observation", is("observation")))
		.andExpect(jsonPath("guests[0].address.id", is(1)))
		.andExpect(jsonPath("guests[0].address.street", is("Street")))
		.andExpect(jsonPath("guests[0].address.city", is("Test")))
		.andExpect(jsonPath("guests[0].address.district", is("District")))
		.andExpect(jsonPath("guests[0].address.number", is("1F")))
		.andExpect(jsonPath("guests[0].address.state", is("SP")))
		.andExpect(jsonPath("guests[0].address.zipCode", is("11111111")))
		.andExpect(jsonPath("guests[1].id", is(2))).andExpect(jsonPath("guests[1].name", is("Guest 2")))
		.andExpect(jsonPath("guests[1].dateOfBirth[0]", is(2001)))
		.andExpect(jsonPath("guests[1].dateOfBirth[1]", is(11)))
		.andExpect(jsonPath("guests[1].dateOfBirth[2]", is(10)))
		.andExpect(jsonPath("guests[1].phoneNumber", is("1166987451")))
		.andExpect(jsonPath("guests[1].celNumber", is("11988887746")))
		.andExpect(jsonPath("guests[1].rg", is("226547854")))
		.andExpect(jsonPath("guests[1].cpf", is("24953683013")))
		.andExpect(jsonPath("guests[1].ministery", is(false)))
		.andExpect(jsonPath("guests[1].baptized", is(false)))
		.andExpect(jsonPath("guests[1].dateOfBaptism[0]", is(2018)))
		.andExpect(jsonPath("guests[1].dateOfBaptism[1]", is(12)))
		.andExpect(jsonPath("guests[1].dateOfBaptism[2]", is(12)))
		.andExpect(jsonPath("guests[1].prayingHouse", is("Central")))
		.andExpect(jsonPath("guests[1].observation", is("observation")))
		.andExpect(jsonPath("guests[1].address.id", is(2)))
		.andExpect(jsonPath("guests[1].address.street", is("Street2")))
		.andExpect(jsonPath("guests[1].address.city", is("Test2")))
		.andExpect(jsonPath("guests[1].address.district", is("District2")))
		.andExpect(jsonPath("guests[1].address.number", is("1G")))
		.andExpect(jsonPath("guests[1].address.state", is("MG")))
		.andExpect(jsonPath("guests[1].address.zipCode", is("22222222")))
		.andExpect(jsonPath("contact.name", is(reservationDto.getContact().getName())))
		.andExpect(jsonPath("contact.phoneNumber", is(reservationDto.getContact().getPhoneNumber())))
		.andExpect(jsonPath("contact.celNumber", is(reservationDto.getContact().getCelNumber())))
		.andExpect(jsonPath("contact.ministery", is(reservationDto.getContact().getMinistery())))
		.andExpect(jsonPath("contact.relationship", is(reservationDto.getContact().getRelationship())))
		.andExpect(jsonPath("contact.observation", is(reservationDto.getContact().getObservation())))
		.andExpect(jsonPath("contact.address.street", is(reservationDto.getContact().getAddress().getStreet())))
		.andExpect(jsonPath("contact.address.city", is(reservationDto.getContact().getAddress().getCity())))
		.andExpect(jsonPath("contact.address.district", is(reservationDto.getContact().getAddress().getDistrict())))
		.andExpect(jsonPath("contact.address.number", is(reservationDto.getContact().getAddress().getNumber())))
		.andExpect(jsonPath("contact.address.state", is(reservationDto.getContact().getAddress().getState())))
		.andExpect(jsonPath("contact.address.zipCode", is(reservationDto.getContact().getAddress().getZipCode())));
		
	}
	
	@Test
	void updateStatusSuccessTest() throws Exception {
		ReservationStatusDto reservationStatusDto = TestUtils.createReservationStatusDto();
		this.mockMvc
				.perform(patch(BY_ID.concat("/status")).content(new ObjectMapper().writeValueAsString(reservationStatusDto))
						.contentType(MediaType.APPLICATION_JSON))
				.andExpect(status().isNoContent());
		
		this.mockMvc.perform(get(BY_ID).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("status", is(reservationStatusDto.getStatus())));
	}
	
	@Test
	void updateStatusErrorTest() throws Exception {
		ReservationStatusDto reservationStatusDto = TestUtils.createReservationStatusDto();
		reservationStatusDto.setStatus("INEXISTING_STATUS");
		String url = BY_ID.concat("/status");
		this.mockMvc
				.perform(patch(url).content(new ObjectMapper().writeValueAsString(reservationStatusDto))
						.contentType(MediaType.APPLICATION_JSON))
				.andExpect(status().isBadRequest())
				.andExpect(jsonPath("timestamp", notNullValue()))
				.andExpect(jsonPath("status", is(400)))
				.andExpect(jsonPath("message", is("Valor incorreto passado. Verifique os dados e tente novamente")))
				.andExpect(jsonPath("error", is("No enum constant br.org.ccb.sgh.entity.Status.INEXISTING_STATUS")))
				.andExpect(jsonPath("path", is(url)));
		
		this.mockMvc.perform(get(BY_ID).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
		.andExpect(jsonPath("status", is("CONFIRMED")));
	}
	
	@Test
	void updateNotFoundTest() throws Exception {
		ReservationDto reservationDto = TestUtils.createReservationDto();
		this.mockMvc
				.perform(put(URL.concat("/99999999")).content(new ObjectMapper().writeValueAsString(reservationDto))
						.contentType(MediaType.APPLICATION_JSON))
				.andExpect(status().isNotFound());
	}
	
	@Test
	void deleteSuccessTest() throws Exception {
		this.mockMvc
				.perform(delete(BY_ID))
				.andExpect(status().isNoContent());
		this.mockMvc.perform(get(BY_ID).contentType(MediaType.APPLICATION_JSON)).andExpect(status().isNotFound());
		
	}
}
