drop table if exists reservations_guests;
drop table if exists Guest;
drop table if exists GuestType;
drop table if exists Reservation;
drop table if exists Contact;
drop table if exists Room;
drop table if exists SupportHouse;
drop table if exists Address;
drop table if exists hibernate_sequence;